spring:
  application:
    name: turbine
server:
  port: 8888
management:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8761/eureka/
turbine:
  app-config: eureka-consumer
  cluster-name-expression: new String("default")
  combine-host-port: true